/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Posts {
  content: string;
  created_at: Generated<string>;
  id: Generated<number>;
  title: string;
  updated_at: Generated<string>;
  user_id: number;
}

export interface Users {
  created_at: Generated<string>;
  email: string;
  id: Generated<number>;
  name: string;
  updated_at: Generated<string>;
}

export interface DB {
  posts: Posts;
  users: Users;
}
